# Site settings
name: Emily Koagedal
title: Emily Koagedal | Software Engineer
description: Technology + Design Innovator
baseurl: ""
email: elkoagedal@berkeley.edu
# cover: https://brittanychiang.com/img/og.png
logo: https://elkoagedal.github.io/img/emojis/technologist.png
resume: https://elkoagedal.github.io/CurrentResume.pdf
social:
  - title: email
    url: elkoagedal@berkeley.edu
  - title: instagram
    url: https://instagram.com/koags
  - title: github
    url: https://github.com/elkoagedal
  - title: linkedin
    url: https://www.linkedin.com/in/EmilyKoagedal

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
